// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AracTipiId")
                        .HasColumnType("int");

                    b.Property<string>("BaslangicKilometresi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DegisiklikTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<short>("DemirbasDurumu")
                        .HasColumnType("smallint");

                    b.Property<short>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<int>("KaydedenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<short>("KilometredeBakimaGider")
                        .HasColumnType("smallint");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ModelYili")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Plakasi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Rengi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Resimleri")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuhsatNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("AracTipiId");

                    b.ToTable("Araclar");
                });

            modelBuilder.Entity("Domain.Entities.AracBeklemeDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BeklemeDurum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DegisiklikTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<short>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<int>("KaydedenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AracBeklemeDurumlari");
                });

            modelBuilder.Entity("Domain.Entities.AracTalep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AracBeklemeDurumId")
                        .HasColumnType("int");

                    b.Property<int?>("AracId")
                        .HasColumnType("int");

                    b.Property<short>("AracTalepDurum")
                        .HasColumnType("smallint");

                    b.Property<string>("BaslangicNoktasi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BitisNoktasi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DegisiklikTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<short>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<DateTime>("GidisTarihSaat")
                        .HasColumnType("datetime2");

                    b.Property<int>("KaydedenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoforId")
                        .HasColumnType("int");

                    b.Property<string>("ToplamKilometre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AracBeklemeDurumId");

                    b.HasIndex("AracId");

                    b.HasIndex("SoforId");

                    b.ToTable("AracTalepleri");
                });

            modelBuilder.Entity("Domain.Entities.AracTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DegisiklikTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<short>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<int>("KaydedenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AracTipleri");
                });

            modelBuilder.Entity("Domain.Entities.Birim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DegisiklikTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<short>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<int>("KaydedenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UstBirimId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UstBirimId");

                    b.ToTable("Birimler");
                });

            modelBuilder.Entity("Domain.Entities.CalismaTur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DegisiklikTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<short>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<int>("KaydedenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CalismaTurleri");
                });

            modelBuilder.Entity("Domain.Entities.Dosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DegisiklikTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<short>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<int>("KaydedenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("RefId")
                        .HasColumnType("int");

                    b.Property<int>("RefTip")
                        .HasColumnType("int");

                    b.Property<string>("Uzanti")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Yol")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dosyalar");
                });

            modelBuilder.Entity("Domain.Entities.Duyuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnaResim")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Basligi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<short>("Begenme")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DegisiklikTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<short>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int>("KaydedenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeywordAlani")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metin")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("SliderGoster")
                        .HasColumnType("smallint");

                    b.Property<int>("SliderSirasi")
                        .HasColumnType("int");

                    b.Property<DateTime>("YayinBitisTarih")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("YayinTarih")
                        .HasColumnType("datetime2");

                    b.Property<short>("YorumEkle")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Duyurular");
                });

            modelBuilder.Entity("Domain.Entities.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DegisiklikTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<short>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<int>("KaydedenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("Domain.Entities.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DegisiklikTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<short>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<int>("KategoriTipId")
                        .HasColumnType("int");

                    b.Property<int>("KaydedenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yetkileri")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriTipId");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("Domain.Entities.KategoriTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DegisiklikTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<short>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<int>("KaydedenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipAdi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("KategoriTipleri");
                });

            modelBuilder.Entity("Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("AskerlikDurum")
                        .HasColumnType("smallint");

                    b.Property<int>("BirimId")
                        .HasColumnType("int");

                    b.Property<int>("CalismaTurId")
                        .HasColumnType("int");

                    b.Property<string>("CepTelefon")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<short>("Cinsiyet")
                        .HasColumnType("smallint");

                    b.Property<string>("DahiliNo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("DegisiklikTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<short>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("EvTelefon")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("FirmaSicilNo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<string>("KanGrubu")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("KaydedenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<short>("MedeniDurum")
                        .HasColumnType("smallint");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("YakiniAdSoyad")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("YakiniTelefon")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("CalismaTurId");

                    b.HasIndex("GorevId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("Domain.Entities.Sofor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DegisiklikTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("DegistirenId")
                        .HasColumnType("int");

                    b.Property<short>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<string>("EhliyetYetkinlikleri")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KaydedenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Soforler");
                });

            modelBuilder.Entity("Domain.Entities.Arac", b =>
                {
                    b.HasOne("Domain.Entities.AracTipi", "AracTipi")
                        .WithMany()
                        .HasForeignKey("AracTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AracTipi");
                });

            modelBuilder.Entity("Domain.Entities.AracTalep", b =>
                {
                    b.HasOne("Domain.Entities.AracBeklemeDurum", "AracBeklemeDurum")
                        .WithMany()
                        .HasForeignKey("AracBeklemeDurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Arac", "Arac")
                        .WithMany()
                        .HasForeignKey("AracId");

                    b.HasOne("Domain.Entities.Sofor", "Sofor")
                        .WithMany()
                        .HasForeignKey("SoforId");

                    b.Navigation("Arac");

                    b.Navigation("AracBeklemeDurum");

                    b.Navigation("Sofor");
                });

            modelBuilder.Entity("Domain.Entities.Birim", b =>
                {
                    b.HasOne("Domain.Entities.Birim", "UstBirim")
                        .WithMany()
                        .HasForeignKey("UstBirimId");

                    b.Navigation("UstBirim");
                });

            modelBuilder.Entity("Domain.Entities.Duyuru", b =>
                {
                    b.HasOne("Domain.Entities.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Domain.Entities.Kategori", b =>
                {
                    b.HasOne("Domain.Entities.KategoriTip", "KategoriTip")
                        .WithMany()
                        .HasForeignKey("KategoriTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategoriTip");
                });

            modelBuilder.Entity("Domain.Entities.Kullanici", b =>
                {
                    b.HasOne("Domain.Entities.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CalismaTur", "CalismaTur")
                        .WithMany()
                        .HasForeignKey("CalismaTurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Gorev", "Gorev")
                        .WithMany()
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Birim");

                    b.Navigation("CalismaTur");

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("Domain.Entities.Sofor", b =>
                {
                    b.HasOne("Domain.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });
#pragma warning restore 612, 618
        }
    }
}
